### PR TITLE
Use node fetch instead of promisfied-https

### PR DESCRIPTION
**Pull request by jonstoneman**
@christav: This probably shouldn't be merged as-is as I had to change `import * as fetch from 'node-fetch'` to `const fetch = require('node-fetch')` to avoid this error:
```
error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof 'node-fetch'' has no compatible call signatures. 
```

### CODE REVIEW

**Comment by jonstoneman** [comment]
@christav  👍    Do you have any advice to help me tackle the typings issues or is that something you should look at?

**Comment by lumaxis** [comment]
@jonstoneman The issue was because `fetch` is using a [default export](https://www.typescriptlang.org/docs/handbook/modules.html#default-exports).
`import fetch from 'node-fetch';` works.

**Comment by jonstoneman** [comment]
Thanks Lukas!  

@christav I've made that change and everything (inc intelisense) is working so I guess this should be good to merge now..

**Comment by christav** [comment]
Going to close this for now, will revisit later.

**Pull request closed without merging**
